### ISSUE TITLE
When will the Llumnix paper be published?

### ISSUE THREAD

**Issue by Jeffwan** [alibaba/llm-scheduling-artifact#1]
Hi Llumnix authors,

I happen to see this repo and thanks for sharing it. Do you have plan to put it on the arvix?

**Comment by zhypku** [comment]
> Hi Llumnix authors,
> 
> I happen to see this repo and thanks for sharing it. Do you have plan to put it on the arvix?

@Jeffwan Hi, we are still working on the camera-ready version of the paper. We will arxiv it when it is ready. Won't be long :)
